#!/bin/sh
#set -eux
VMNAME="alpine-$(date +%Y%m%d-%H%M%S)"
export PACKER_LOG=1
export PACKER_LOG_PATH="packerlog_$(date +%Y%m%d-%H%M%S).txt"
# Generate random password for root
rootpassword=$(tr -dc 'A-Za-z0-9"#$%()*+,-./:;<=>?@[\]_{}~' </dev/urandom | head -c 13)
# Building image
packer build -force -var "password=${rootpassword}" -var "vm="${VMNAME}"" packer.json 
# Create http server 
#python3 -m http.server > /dev/null 2>&1 &
#pyd=$!
# Publish image on nutanix cluster for testing 
#URL="http://xxx.xxx.xxx.xxx:8000/images/$VMNAME.qcow2"
#bash publishoncluster.sh parameter1 parameter2 parameter3
# Kill http server
#kill $pyd
