#!/bin/sh
set -eux
DIR=$(dirname "$0")
# Set log file
LOG="${DIR}/buildlog_$(date +%Y-%m-%d_%Hh%M).log"
touch "${LOG}"
exec 1>"${LOG}"
exec 2>&1
curl -sSL https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso -o ${DIR}/virtio-win.iso
VMNAME="windows2022-fr-FR-datacenter-uefi-$(date +%Y%m%d-%H%M%S)"
export PACKER_LOG=1
export PACKER_LOG_PATH="${DIR}/packerlog_$(date +%Y-%m-%d_%Hh%M).log"
# Building image
iso=$(ls ${DIR}/OS_ISO) # TODO if multiple iso get the most recent
sha=$(sha256sum ${DIR}/OS_ISO/${iso} | awk -F " " '{print $1}')
packer build -force -var "virtio_win_iso=${DIR}/virtio-win.iso" -var "iso_url=${DIR}/OS_ISO/${iso}" -var "iso_checksum=sha256:${sha}" -var "dir"=${DIR} -var "vm_name="${VMNAME}"" ${DIR}/packer.json
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/ovh/metis ${DIR}/images/${VMNAME}.qcow2 ovh@10.2.0.201:http/qcow2/windows2022-fr-FR-uefi-datacenter.qcow2
