#!/bin/sh
set -eux
DIR=$(dirname $0)
# Set log file
LOG="${DIR}/buildlog_$(date +%Y-%m-%d_%Hh%M).log"
touch "${LOG}"
exec 1>"${LOG}"
exec 2>&1
curl -sSL https://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/debian-testing-amd64-netinst.iso -o ${DIR}/OS_ISO/debian-testing-amd64-netinst.iso
VMNAME="debian13-uefi-$(date +%Y%m%d-%H%M%S)"
export PACKER_LOG=1
export PACKER_LOG_PATH="${DIR}/packerlog_$(date +%Y-%m-%d_%Hh%M).log"
# Building image
iso=$(ls ${DIR}/OS_ISO) # TODO if multiple iso get the most recent
sha=$(sha256sum ${DIR}/OS_ISO/${iso} | awk -F " " '{print $1}')
packer build -force -var "dir=${DIR}" -var "iso_url=${DIR}/OS_ISO/${iso}" -var "iso_checksum=sha256:${sha}" -var "vm_name="${VMNAME}"" ${DIR}/packer.json
