#!/bin/sh
set -eux
createhttpdserver() {
# Create http server 
cd "${DIR}/images/" 
python3 -m http.server > /dev/null 2>&1 &
pyd=$!
export BLA="$pyd"
}

ALPINEVERSION="alpine3213"
DIR="$(dirname $0)"
IMGNAME="${ALPINEVERSION}-cloudinit.qcow2"
# Set log file
LOG="${DIR}/buildlog_$(date +%Y-%m-%d_%Hh%M).log"
touch "${LOG}"
exec 1>"${LOG}"
exec 2>&1
VMNAME="${ALPINEVERSION}-cloudinit-$(date +%Y%m%d-%H%M%S)"
export PACKER_LOG=1
export PACKER_LOG_PATH="${DIR}/packerlog_$(date +%Y-%m-%d_%Hh%M).log"
# Generate random password for root
rootpassword=$(tr -dc 'A-Za-z0-9"#$%()*+,-./:;<=>?@[\]_{}~' </dev/urandom | head -c 30)
# Building image
packer build -force -var "dir=${DIR}" -var "password=${rootpassword}" -var "vm="${VMNAME}"" ${DIR}/packer.json 
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/ovh/metis ${DIR}/images/$VMNAME.qcow2  ovh@10.2.0.201:http/qcow2/$IMGNAME
# Publish image on nutanix cluster for testing 
#createhttpdserver
#URL="http://51.210.251.66:8000/$VMNAME.qcow2"
#bash ${DIR}/publishoncluster.sh "T4I+st~AEcvVS2OF" "cluster-1449.nutanix.ovh.net" "$URL"
