#!/bin/sh
set -eux
ALPINEVERSION="alpine3213"
DIR="$(dirname $0)"
IMGNAME="${ALPINEVERSION}-cloudinit.qcow2"
# Set log file
LOG="${DIR}/buildlog_$(date +%Y-%m-%d_%Hh%M).log"
touch "${LOG}"
exec 1>"${LOG}"
exec 2>&1
VMNAME="${ALPINEVERSION}-cloudinit-$(date +%Y%m%d-%H%M%S)"
export PACKER_LOG=1
export PACKER_LOG_PATH="${DIR}/packerlog_$(date +%Y-%m-%d_%Hh%M).log"
# Generate random password for root
rootpassword=$(tr -dc 'A-Za-z0-9"#$%()*+,-./:;<=>?@[\]_{}~' </dev/urandom | head -c 30)
# Building image
packer build -force -var "dir=${DIR}" -var "password=${rootpassword}" -var "vm="${VMNAME}"" ${DIR}/packer.json 
